<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_tipe_xui.UI.TreeGrid-CMDa-r_a_edit</name>
   <tag></tag>
   <elementGuidId>ceccf559-9eb5-4527-87c2-e2e45603cfbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='xui.UI.TreeGrid-CMD:a:-r_a_edit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Ubah&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ee08449-1eaf-4905-ba17-4464ba941dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ubah</value>
      <webElementGuid>12889199-b570-4440-9e6d-d8495e31e95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>61ce9cd2-3ff9-4faf-86f1-437b3795021f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.TreeGrid-CMD:a:-r_a_edit</value>
      <webElementGuid>83d91833-53ff-4f4f-987e-090a4869366c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-image xui-node-image-hover xui-treegrid-cmd xui-treegrid-cmd-hover xui-node xui-node-hover xui-tag-cmd xui-tag-cmd-hover fa fa-hover fa-lg fa-lg-hover fa-edit fa-edit-hover xui-custom xui-custom-hover</value>
      <webElementGuid>36434479-aa86-4712-b32a-cf742c4f89aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.TreeGrid-CMD:a:-r_a_edit&quot;)</value>
      <webElementGuid>d35047fd-e273-4a3c-9532-b826fa769b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='xui.UI.TreeGrid-CMD:a:-r_a_edit']</value>
      <webElementGuid>8f594adb-5713-492b-b407-77a590a890e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-LTAGCMDS:a:-r_a']/img</value>
      <webElementGuid>eb8a001f-ba4f-4a36-a44b-4a5f5adb43f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Ubah']</value>
      <webElementGuid>0ca562a0-f513-45e0-bcde-9a03dd111755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/img</value>
      <webElementGuid>0d9eb7ba-def4-423a-b2e3-89f855cb4fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Ubah' and @id = 'xui.UI.TreeGrid-CMD:a:-r_a_edit']</value>
      <webElementGuid>e9094889-cf82-4e9b-b217-dc7f55b2a267</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
