<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_tipe_xui.UI.TreeGrid-CMDa-r_a_del</name>
   <tag></tag>
   <elementGuidId>09336228-0732-40e7-812f-27c598890b4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='xui.UI.TreeGrid-CMD:a:-r_a_del']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Hapus&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>727d5b21-4d16-4710-ba49-7735ff6432ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hapus</value>
      <webElementGuid>e31148fc-d891-4e8d-99dd-cba3fe705813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3089379e-fda7-4986-b945-01a30a3f610e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.TreeGrid-CMD:a:-r_a_del</value>
      <webElementGuid>7a409309-19f9-46c6-8e84-369675be8c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-image xui-node-image-hover xui-treegrid-cmd xui-treegrid-cmd-hover xui-node xui-node-hover xui-tag-cmd xui-tag-cmd-hover fa fa-hover fa-lg fa-lg-hover fa-trash fa-trash-hover xui-custom xui-custom-hover</value>
      <webElementGuid>5ab63c90-d171-4b17-841e-64ac8c33af1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.TreeGrid-CMD:a:-r_a_del&quot;)</value>
      <webElementGuid>7593ad30-e2a1-40a7-ae35-d232c8b83d85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='xui.UI.TreeGrid-CMD:a:-r_a_del']</value>
      <webElementGuid>97856873-7057-4f6c-bb6f-855baa6a5d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-LTAGCMDS:a:-r_a']/img[2]</value>
      <webElementGuid>380bbb5d-7cd3-4d3e-988d-111a2ddab632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Hapus']</value>
      <webElementGuid>b8d926a1-4def-4e4a-87e9-084fe36af6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>ab6f1f10-4cdf-40fb-abd0-4a383ca70ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Hapus' and @id = 'xui.UI.TreeGrid-CMD:a:-r_a_del']</value>
      <webElementGuid>c4f20493-0407-420c-b313-45f3ac477639</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
