<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Kategori</name>
   <tag></tag>
   <elementGuidId>89fa2b18-0ec2-4b34-bd36-e7145a9a9b46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='xui.UI.Label:aa:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:has-text=&quot;Kategori*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>796b84a7-6be9-49f7-be13-a8191057e7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Label:aa:</value>
      <webElementGuid>091f5fbb-32e6-4048-95f2-592753f331f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-label xui-node-label-hover xui-label xui-label-hover  xui-ui-ctrl xui-ui-ctrl-hover xui-ui-selectable xui-ui-selectable-hover      xui-custom xui-custom-hover</value>
      <webElementGuid>47081b71-8b05-4c44-8774-f3f92931c4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori*</value>
      <webElementGuid>d25a0dfc-cf02-4e09-825b-9ac3de005922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Label:aa:&quot;)</value>
      <webElementGuid>44a7b0ed-8527-4126-8ac5-76a2c8eaa942</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='xui.UI.Label:aa:']</value>
      <webElementGuid>e79cec5e-d266-4912-88ef-ed40a614921d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Tabs-PANEL:a:a']/label[2]</value>
      <webElementGuid>ea06f60e-9d21-4c0b-84a8-3260b712ac97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST'])[2]/following::label[1]</value>
      <webElementGuid>2d21ca24-1a59-40eb-aa1a-978913c48c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATA PERSETUJUAN RANGE APU/PPT'])[1]/following::label[2]</value>
      <webElementGuid>40bff482-0f62-452a-a547-058b1b4dcf2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekening Bermasalah'])[2]/preceding::label[1]</value>
      <webElementGuid>5067d9fa-7d59-42db-a48c-defbf780cf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/label[2]</value>
      <webElementGuid>7679d86a-a770-43be-89df-350deeaa1ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'xui.UI.Label:aa:' and (text() = 'Kategori*' or . = 'Kategori*')]</value>
      <webElementGuid>5e9bca0a-1c7f-4065-a3db-b9450d8d1f5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
