<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>60d00079-9f80-47eb-a624-12eb2a9f1a35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='xui.UI.PageBar-LAST:a:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;2&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f65911b-48ea-4395-b1b9-8aad94a87ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#2</value>
      <webElementGuid>006ebba6-fab4-4d24-ba9c-4b1388c5fd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d6d20434-299a-4571-9e7c-d1d6da931494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.PageBar-LAST:a:</value>
      <webElementGuid>2c318dda-e2e7-44f2-a694-cd513139a05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-a xui-node-a-hover xui-pagebar-last xui-pagebar-last-hover xui-ui-btn xui-ui-btn-hover xui-uibar xui-uibar-hover xui-uigradient xui-uigradient-hover xui-uiborder-radius xui-uiborder-radius-hover xui-custom xui-custom-hover</value>
      <webElementGuid>2e4ac47c-ebc4-4ec4-8d8a-6ddbcf5e16e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>be5d9626-c1be-44ed-8040-76d722335ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ffd689ed-ba87-4237-90a9-0ffa99fc9b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.PageBar-LAST:a:&quot;)</value>
      <webElementGuid>2b3bef63-0369-4c18-8bc9-8b110d2af56e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='xui.UI.PageBar-LAST:a:']</value>
      <webElementGuid>0599c861-a4ac-4cb4-a14d-75ade90bae57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.PageBar:a:']/a[6]</value>
      <webElementGuid>76775800-23c3-441b-8962-8f47b81a1973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'2')])[2]</value>
      <webElementGuid>e379545e-8551-4997-9722-4cab6b3c19eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PARAMETER RANGE APU/PPT'])[2]/following::a[6]</value>
      <webElementGuid>342dd224-3558-486b-9eb9-b471b53d2eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PARAMETER RANGE APU/PPT'])[1]/following::a[6]</value>
      <webElementGuid>725ac911-4e8a-4463-b87c-0e9eba4d5c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian'])[1]/preceding::a[1]</value>
      <webElementGuid>a8cd0f28-536d-480f-a4a6-e53e6425ca4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampil'])[1]/preceding::a[1]</value>
      <webElementGuid>75d9e3ff-9a6f-4aa6-944a-7dd604301197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#2')])[2]</value>
      <webElementGuid>46c0c47d-fc2e-4f4c-8b6e-ada9115ba797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>75d8fac5-a3a2-4d39-992e-6c18f8552c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#2' and @id = 'xui.UI.PageBar-LAST:a:' and @title = '2' and (text() = '2' or . = '2')]</value>
      <webElementGuid>86f18727-5c9f-4cf6-9800-32abe4ba0544</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
